build:
  environment:
    php: '7.2'
    hosts:
      laravel.dev: '127.0.0.1'
    variables:
  cache:
    directories:
      - vendor/
      - ~/.composer/cache/
  dependencies:
  tests:
    override:
      -
        command: vendor/bin/phpunit --coverage-clover=laravel-test-examples-coverage
        coverage:
          file: laravel-test-examples-coverage
          format: clover
